### ISSUE TITLE
License choice

### ISSUE THREAD

**Issue by breadcentric** [JackyHOz/TrackDetection#1]
This is a great resource! I'm sharing your content here: https://blog.deepracing.io/2021/03/28/analyse-aws-deepracer-real-world-performance-using-amazon-rekognition-custom-labels/
Would you be willing to put a license declaration for the piece of mind of those using your project?
Thanks!
Tomasz Ptak

**Comment by JackyHOz** [comment]
> This is a great resource! I'm sharing your content here: https://blog.deepracing.io/2021/03/28/analyse-aws-deepracer-real-world-performance-using-amazon-rekognition-custom-labels/
> Would you be willing to put a license declaration for the piece of mind of those using your project?
> Thanks!
> Tomasz Ptak

**Comment by wpcww** [comment]
License has been attached. Thanks for your sharing and comment!
